version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
#    environment:
#      - WEBAPPBOT_BACKEND_PORT=8000
#      - WEBAPPBOT_URL=https://webappbot.website
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./sslcert:/etc/nginx/conf.d/sslcert
#      - .env:/app/.env
      - .:/app
