version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./sslcert:/etc/nginx/conf.d/sslcert
      - .:/app
